---
title: "ARS_Analysis"
author: "Erica Griffin"
date: "2025-10-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(dplyr)
library(lme4)
library(MASS)
library(lmerTest)
library(visreg)
library(car)
library(DHARMa)
library(rptR)
library(texreg)
library(apaTables)
nest <- read.csv("/Users/ericagriffin/Library/CloudStorage/Box-Box/projects/Griffin et al. 2025 KRSP/fitness-attentiveness/AnalysisData/nest_binary.csv") # add in both datasets 
nest_censored <- read.csv("/Users/ericagriffin/Library/CloudStorage/Box-Box/projects/Griffin et al. 2025 KRSP/fitness-attentiveness/AnalysisData/nest_censored.csv") # add in both datasets
nest_censored <- nest_censored %>% # make sure only mom's that do return are included in the latency model 
  filter(m_return == "y")
## Get an additional numeric binary for m_return 
nest$m_return_numeric <- ifelse(nest$m_return == "n", 0, 1) # get a numerical value to be used in models - did mom return yes or no
## make nest categorical 
nest$nest <- factor(nest$nest)
nest_censored$nest <- factor(nest_censored$nest)
```

# Repeatability analyses: 

### m_return

```{r}
repeatability_binary <- rptBinary(m_return_numeric ~ (1|squirrel_id), grname = "squirrel_id", data = nest, link = c("logit", "probit"),
  CI = 0.95, nboot = 1000, npermut = 0, parallel = FALSE,
  ncores = NULL, ratio = TRUE, adjusted = TRUE, expect = "meanobs",
  rptObj = NULL, update = FALSE)
summary(repeatability_binary)
```

### scaled_latency

```{r}
repeatability_censored <- rpt(return_lat ~ (1|squirrel_id), data = nest_censored, datatype = "Gaussian", grname = "squirrel_id")
summary(repeatability_censored)
```


Here I am centering mom_age before squaring it to reduce multicollinearity
```{r}
nest$mom_age_c <- scale(nest$mom_age, scale = FALSE) 
nest$mom_age_c2 <- nest$mom_age_c^2

nest_censored$mom_age_c <- scale(nest_censored$mom_age, scale = FALSE) 
nest_censored$mom_age_c2 <- nest_censored$mom_age_c^2
```

Here, I am going to create subsets of each data file so that way I run seperate models for nest 1 and nest 2 for both m_return and latency. 

```{r}

nest_nest1 <- nest %>%
  filter(nest == "1")

nest_nest2 <- nest %>%
  filter(nest == "2")


nestcensored_nest1 <- nest_censored %>%
  filter(nest == "1")

nestcensored_nest2 <- nest_censored %>%
  filter(nest == "2")
```


## ARS ~ M_return (Nest 1)
```{r}
ARS_m_return_nest1 <- glmer(
  ARS ~ mom_age_c + mom_age_c2 +
    m_return * scaled_density +  
    m_return * year + 
    m_return * predator + 
    scaled_julian_date * year + 
    scaled_julian_date * scaled_density + 
    (1 | grid_year) + 
    (1 | squirrel_id) + 
    offset(log(n_pups)),
  data = nest_nest1,
  family = poisson,
  control = glmerControl(optimizer = "bobyqa")
)
summary(ARS_m_return_nest1)
nobs(ARS_m_return_nest1)
```


## ARS ~ M_return (Nest 2)
```{r}
ARS_m_return_nest2 <- glmer(
  ARS ~ mom_age_c + mom_age_c2 +
    m_return * scaled_density +  
    m_return * year + 
    m_return * predator + 
    scaled_julian_date * year + 
    scaled_julian_date * scaled_density + 
    (1 | grid_year) + 
    (1 | squirrel_id) + 
    offset(log(n_pups)),
  data = nest_nest2,
  family = poisson,
  control = glmerControl(optimizer = "bobyqa")
)
summary(ARS_m_return_nest2)
nobs(ARS_m_return_nest2)
```


## ARS ~ latency (Nest 1)
```{r}
ARS_lat_nest1 <- glmer(
  ARS ~ mom_age_c + mom_age_c2 +
    scaled_lat * scaled_density +  
    scaled_lat * year + 
    scaled_lat * predator + 
    scaled_julian_date * year + 
    scaled_julian_date * scaled_density + 
    (1 | grid_year) + 
    (1 | squirrel_id) + 
    offset(log(n_pups)),
  data = nestcensored_nest1,
  family = poisson,
  control = glmerControl(optimizer = "bobyqa")
)
summary(ARS_lat_nest1)
nobs(ARS_lat_nest1)
```

## ARS ~ latency (Nest 2)
```{r}
ARS_lat_nest2 <- glmer(
  ARS ~ mom_age_c + mom_age_c2 +
    scaled_lat * scaled_density +  
    scaled_lat * year + 
    scaled_lat * predator + 
    scaled_julian_date * year + 
    scaled_julian_date * scaled_density + 
    (1 | grid_year) + 
    (1 | squirrel_id) + 
    offset(log(n_pups)),
  data = nestcensored_nest2,
  family = poisson,
  control = glmerControl(optimizer = "bobyqa")
)
summary(ARS_lat_nest2)
nobs(ARS_lat_nest2)
```

