---
title: "ARS_Analysis"
author: "Erica Griffin"
date: "2025-10-27"
output: html_document
---
```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(dplyr)
library(lme4)
library(MASS)
library(lmerTest)
library(visreg)
library(car)
library(DHARMa)
library(rptR)
library(texreg)
library(apaTables)
binary_ARS <- read.csv("/Users/ericagriffin/Library/CloudStorage/Box-Box/projects/2025 - Griffin et al. KRSP/fitness-attentiveness/AnalysisData/ARS_binary.csv") # add in both datasets 
latency_ARS <- read.csv("/Users/ericagriffin/Library/CloudStorage/Box-Box/projects/2025 - Griffin et al. KRSP/fitness-attentiveness/AnalysisData/ARS_latency.csv") # add in both datasets
LRS <- read.csv("/Users/ericagriffin/Library/CloudStorage/Box-Box/projects/2025 - Griffin et al. KRSP/fitness-attentiveness/AnalysisData/LRS.csv")
```

# Repeatability analyses: 

### m_return

```{r}
repeatability_binary <- rptBinary(m_return_numeric ~ (1|squirrel_id), grname = "squirrel_id", data = binary_ARS, link = c("logit", "probit"),
  CI = 0.95, nboot = 1000, npermut = 0, parallel = FALSE,
  ncores = NULL, ratio = TRUE, adjusted = TRUE, expect = "meanobs",
  rptObj = NULL, update = FALSE)
summary(repeatability_binary)
```

### scaled_latency

```{r}
repeatability_censored <- rpt(return_lat ~ (1|squirrel_id), data = latency_ARS, datatype = "Gaussian", grname = "squirrel_id")
summary(repeatability_censored)
```

# LRS Analyses: 

```{r}
LRS_model1 <- glmer.nb(LRS ~ scaled_lat + mast_encounter1 + scaled_lat*mast_encounter1 + scaled_long + exp + (1 | observations), data = LRS) 
summary(LRS_model1)
```

```{r}
LRS_model2 <- glmer.nb(LRS ~ percent_return + mast_encounter1 + percent_return*mast_encounter1 + scaled_long + exp + (1 | observations), data = LRS) 
summary(LRS_model2)
```

# ARS Analyses: 

## ARS ~ M_return (Nest 1)
```{r}
binary_nest1 <- binary_ARS %>% filter(nest == 1) # only include nest intrusion 1 
ARS_m_return_nest1 <- glmer(
  ARS ~ scaled_mom_age + scaled_mom_age_squared +
    m_return * scaled_density +  
    m_return * year + 
    m_return * predator + 
    scaled_julian_date * year + 
    scaled_julian_date * scaled_density + 
    (1 | grid_year) + 
          (1 | squirrel_id) + 
    offset(log(n_pups)),
  data = binary_nest1,
  family = poisson,
  control = glmerControl(optimizer = "bobyqa")
)
summary(ARS_m_return_nest1)
nobs(ARS_m_return_nest1)
```


## ARS ~ M_return (Nest 2)
```{r}
binary_nest2 <- binary_ARS %>% filter(nest == "2") # only include nest intrusion 2 
ARS_m_return_nest2 <- glmer(
  ARS ~ scaled_mom_age + scaled_mom_age_squared +
    m_return * scaled_density +  
    m_return * year + 
    m_return * predator + 
    scaled_julian_date * year + 
    scaled_julian_date * scaled_density + 
    (1 | grid_year) + 
      (1 | squirrel_id) + 
    offset(log(n_pups)),
  data = binary_nest2,
  family = poisson,
  control = glmerControl(optimizer = "bobyqa")
)
summary(ARS_m_return_nest2)
nobs(ARS_m_return_nest2)
```


## ARS ~ latency (Nest 1)
```{r}
continuous_nest1 <- latency_ARS %>% filter(nest == "1") # only include nest intrusion 1 
ARS_lat_nest1 <- glmer(
  ARS ~ scaled_mom_age + scaled_mom_age_squared +
    scaled_lat * scaled_density +  
    scaled_lat * year + 
    scaled_lat * predator + 
    scaled_julian_date * year + 
    scaled_julian_date * scaled_density + 
        (1 | grid_year) + 
    offset(log(n_pups)),
  family = poisson,
  control = glmerControl(optimizer = "bobyqa"),
  data = continuous_nest1
)
summary(ARS_lat_nest1)
nobs(ARS_lat_nest1)
```

## ARS ~ latency (Nest 2)
```{r}
continuous_nest2 <- latency_ARS %>% filter(nest == "2") # only include nest intrusion 2 
ARS_lat_nest2 <- glmer(
  ARS ~ scaled_mom_age + scaled_mom_age_squared +
    scaled_lat * scaled_density +  
    scaled_lat * year + 
    scaled_lat * predator + 
    scaled_julian_date * year + 
    scaled_julian_date * scaled_density + 
    (1 | grid_year) + 
    offset(log(n_pups)),
  data = continuous_nest2,
  family = poisson,
  control = glmerControl(optimizer = "bobyqa")
)
summary(ARS_lat_nest2)
nobs(ARS_lat_nest2)
```

