---
title: "LRS_Analysis"
author: "Erica Griffin"
date: "2025-10-27"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(dplyr)
library(lme4)
library(MASS)
library(lmerTest)
library(visreg)
library(car)
library(DHARMa)
library(rptR)
library(texreg)
library(apaTables)
library(viridis)
library(ggpubr)
LRS <- read.csv("/Users/ericagriffin/Library/CloudStorage/Box-Box/projects/2025 - Griffin et al. KRSP/fitness-attentiveness/AnalysisData/LRS.csv")
```

```{r}
LRS_model1 <- glmer.nb(LRS ~ scaled_lat + mast_encounter1 + scaled_lat*mast_encounter1 + scaled_long + exp + (1 | observations), data = LRS) 
summary(LRS_model1)
```

```{r}
LRS_model2 <- glmer.nb(LRS ~ percent_return + mast_encounter1 + percent_return*mast_encounter1 + scaled_long + exp + (1 | observations), data = LRS) 
summary(LRS_model2)
```

```{r}
viridis_colors <- viridis(10)
custom_colors <- c(viridis_colors[3], viridis_colors[8])
scaled_latfigure <- visreg(LRS_model1,
                                      "scaled_lat", by = "mast_encounter1",
                                      gg = T, overlay = T,
                                      xlab = "Average Scaled Latency to Return to Nest (seconds)",
                                      ylab = "Lifetime Reproductive Success",
                                      point = list(alpha = 0.5,
                                                   size = 3),
                                      fill = list(alpha = 0)) +
  scale_color_manual(values = custom_colors, labels = c("No", "Yes")) +
  scale_fill_manual(values = custom_colors, labels = c("No", "Yes")) +
  labs(color = "Mast Encounter?", fill = "Mast Encounter?") +
  theme_classic() +
  labs_pubr() + 
theme(axis.text = element_text(size = 12),
        legend.text = element_text(size = 14),
        axis.title = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.position = "bottom",
        plot.margin = margin(15, 15, 30, 30),
        axis.title.y = element_text(vjust = 5),
        axis.title.x = element_text(vjust = -1),
        plot.tag = element_text(size = 22,
                                face = "bold"))
scaled_latfigure
ggsave("/Users/ericagriffin/Library/CloudStorage/Box-Box/projects/2025 - Griffin et al. KRSP/fitness-attentiveness/Figures/Figure1.png", plot = scaled_latfigure)

```

```{r}
viridis_colors <- viridis(10)
custom_colors <- c(viridis_colors[3], viridis_colors[8])

percentreturn <- visreg(LRS_model2,
                        "percent_return", by = "mast_encounter1",
                        gg = TRUE, overlay = TRUE,
                        xlab = "Percentage of Times Female Returned to Nest",
                        ylab = "Lifetime Reproductive Success",
                        point = list(alpha = 0.5, size = 3),
                        fill = list(alpha = 0)) +
  scale_color_manual(values = custom_colors, labels = c("No", "Yes")) +
  scale_fill_manual(values = custom_colors, labels = c("No", "Yes")) +
  labs(color = "Mast Encounter?", fill = "Mast Encounter?", linetype = "Mast Encounter?") +
  theme_classic() +
  labs_pubr() +
  theme(axis.text = element_text(size = 12),
        legend.text = element_text(size = 14),
        axis.title = element_text(size = 12),
        legend.title = element_text(size = 12),
        legend.position = "bottom",
        plot.margin = margin(15, 15, 30, 30),
        axis.title.y = element_text(vjust = 5),
        axis.title.x = element_text(vjust = -1),
        plot.tag = element_text(size = 22, face = "bold")) 

print(percentreturn)
ggsave("/Users/ericagriffin/Library/CloudStorage/Box-Box/projects/2025 - Griffin et al. KRSP/fitness-attentiveness/Figures/Figure2.png", plot = percentreturn)
```